services:
  hyperf:
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    restart: always
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_PROJECT=hyperf"
      - "APP_SYSTEM_ENV=docker"
    working_dir: "/opt/www"
    ports:
      - 9501:9501
      - 9502:9502
      - 9503:9503
    volumes:
      - ./:/opt/www
    entrypoint: ["php", "watch", "-c"]

  mysql:
    image: mysql:5.7.44-oraclelinux7
    platform: linux/amd64
    environment:
      - "TZ=Asia/Shanghai"
      - MYSQL_ROOT_PASSWORD=12345678
      - "explicit_defaults_for_timestamp=true"
      - "lower_case_table_names=1"
    volumes:
      - ./docker/mysql/57/my.cnf:/etc/my.cnf/:ro
      - ./docker/mysql/57/data:/var/lib/mysql/:rw
      - ./docker/mysql/57/logs:/var/log/mysql/:rw
    ports:
      - 3306:3306
    restart: always

  redis:
    image: redis
    restart: always
